/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class recipeNo013_PassArrayBack */

#ifndef _Included_recipeNo013_PassArrayBack
#define _Included_recipeNo013_PassArrayBack
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     recipeNo013_PassArrayBack
 * Method:    passBooleanArray
 * Signature: ([Z)V
 */
JNIEXPORT void JNICALL Java_recipeNo013_PassArrayBack_passBooleanArray
  (JNIEnv *, jclass, jbooleanArray);

/*
 * Class:     recipeNo013_PassArrayBack
 * Method:    passByteArray
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_recipeNo013_PassArrayBack_passByteArray
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     recipeNo013_PassArrayBack
 * Method:    passCharArray
 * Signature: ([C)V
 */
JNIEXPORT void JNICALL Java_recipeNo013_PassArrayBack_passCharArray
  (JNIEnv *, jclass, jcharArray);

/*
 * Class:     recipeNo013_PassArrayBack
 * Method:    passShortArray
 * Signature: ([S)V
 */
JNIEXPORT void JNICALL Java_recipeNo013_PassArrayBack_passShortArray
  (JNIEnv *, jclass, jshortArray);

/*
 * Class:     recipeNo013_PassArrayBack
 * Method:    passIntArray
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_recipeNo013_PassArrayBack_passIntArray
  (JNIEnv *, jclass, jintArray);

/*
 * Class:     recipeNo013_PassArrayBack
 * Method:    passLongArray
 * Signature: ([J)V
 */
JNIEXPORT void JNICALL Java_recipeNo013_PassArrayBack_passLongArray
  (JNIEnv *, jclass, jlongArray);

/*
 * Class:     recipeNo013_PassArrayBack
 * Method:    passFloatArray
 * Signature: ([F)V
 */
JNIEXPORT void JNICALL Java_recipeNo013_PassArrayBack_passFloatArray
  (JNIEnv *, jclass, jfloatArray);

/*
 * Class:     recipeNo013_PassArrayBack
 * Method:    passDoubleArray
 * Signature: ([D)V
 */
JNIEXPORT void JNICALL Java_recipeNo013_PassArrayBack_passDoubleArray
  (JNIEnv *, jclass, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
