/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class recipeNo009_PassString */

#ifndef _Included_recipeNo009_PassString
#define _Included_recipeNo009_PassString
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     recipeNo009_PassString
 * Method:    displayString
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_recipeNo009_PassString_displayString
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
