/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class recipeNo012_PassArray */

#ifndef _Included_recipeNo012_PassArray
#define _Included_recipeNo012_PassArray
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     recipeNo012_PassArray
 * Method:    passBooleanArray
 * Signature: ([Z)V
 */
JNIEXPORT void JNICALL Java_recipeNo012_PassArray_passBooleanArray
  (JNIEnv *, jclass, jbooleanArray);

/*
 * Class:     recipeNo012_PassArray
 * Method:    passByteArray
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_recipeNo012_PassArray_passByteArray
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     recipeNo012_PassArray
 * Method:    passCharArray
 * Signature: ([C)V
 */
JNIEXPORT void JNICALL Java_recipeNo012_PassArray_passCharArray
  (JNIEnv *, jclass, jcharArray);

/*
 * Class:     recipeNo012_PassArray
 * Method:    passShortArray
 * Signature: ([S)V
 */
JNIEXPORT void JNICALL Java_recipeNo012_PassArray_passShortArray
  (JNIEnv *, jclass, jshortArray);

/*
 * Class:     recipeNo012_PassArray
 * Method:    passIntArray
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_recipeNo012_PassArray_passIntArray
  (JNIEnv *, jclass, jintArray);

/*
 * Class:     recipeNo012_PassArray
 * Method:    passLongArray
 * Signature: ([J)V
 */
JNIEXPORT void JNICALL Java_recipeNo012_PassArray_passLongArray
  (JNIEnv *, jclass, jlongArray);

/*
 * Class:     recipeNo012_PassArray
 * Method:    passFloatArray
 * Signature: ([F)V
 */
JNIEXPORT void JNICALL Java_recipeNo012_PassArray_passFloatArray
  (JNIEnv *, jclass, jfloatArray);

/*
 * Class:     recipeNo012_PassArray
 * Method:    passDoubleArray
 * Signature: ([D)V
 */
JNIEXPORT void JNICALL Java_recipeNo012_PassArray_passDoubleArray
  (JNIEnv *, jclass, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
