/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class recipeNo002_PassInt */

#ifndef _Included_recipeNo002_PassInt
#define _Included_recipeNo002_PassInt
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     recipeNo002_PassInt
 * Method:    displayInt
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_recipeNo002_PassInt_displayInt
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
