/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class recipeNo011_ReturnPrimitive */

#ifndef _Included_recipeNo011_ReturnPrimitive
#define _Included_recipeNo011_ReturnPrimitive
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     recipeNo011_ReturnPrimitive
 * Method:    getBoolean
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_recipeNo011_ReturnPrimitive_getBoolean
  (JNIEnv *, jclass);

/*
 * Class:     recipeNo011_ReturnPrimitive
 * Method:    getByte
 * Signature: ()B
 */
JNIEXPORT jbyte JNICALL Java_recipeNo011_ReturnPrimitive_getByte
  (JNIEnv *, jclass);

/*
 * Class:     recipeNo011_ReturnPrimitive
 * Method:    getChar
 * Signature: ()C
 */
JNIEXPORT jchar JNICALL Java_recipeNo011_ReturnPrimitive_getChar
  (JNIEnv *, jclass);

/*
 * Class:     recipeNo011_ReturnPrimitive
 * Method:    getShort
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_recipeNo011_ReturnPrimitive_getShort
  (JNIEnv *, jclass);

/*
 * Class:     recipeNo011_ReturnPrimitive
 * Method:    getInt
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_recipeNo011_ReturnPrimitive_getInt
  (JNIEnv *, jclass);

/*
 * Class:     recipeNo011_ReturnPrimitive
 * Method:    getLong
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_recipeNo011_ReturnPrimitive_getLong
  (JNIEnv *, jclass);

/*
 * Class:     recipeNo011_ReturnPrimitive
 * Method:    getFloat
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_recipeNo011_ReturnPrimitive_getFloat
  (JNIEnv *, jclass);

/*
 * Class:     recipeNo011_ReturnPrimitive
 * Method:    getDouble
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_recipeNo011_ReturnPrimitive_getDouble
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
