/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class recipeNo014_CreateArray */

#ifndef _Included_recipeNo014_CreateArray
#define _Included_recipeNo014_CreateArray
#ifdef __cplusplus
extern "C" {
#endif
#undef recipeNo014_CreateArray_arraySize
#define recipeNo014_CreateArray_arraySize 5L
/*
 * Class:     recipeNo014_CreateArray
 * Method:    createBooleanArray
 * Signature: (I)[Z
 */
JNIEXPORT jbooleanArray JNICALL Java_recipeNo014_CreateArray_createBooleanArray
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
