/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class recipeNo010_ReturnString */

#ifndef _Included_recipeNo010_ReturnString
#define _Included_recipeNo010_ReturnString
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     recipeNo010_ReturnString
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_recipeNo010_ReturnString_getString
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
