/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class recipeNo015_SigSegvNoHandler */

#ifndef _Included_recipeNo015_SigSegvNoHandler
#define _Included_recipeNo015_SigSegvNoHandler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     recipeNo015_SigSegvNoHandler
 * Method:    callRiskyCodeNoHandler
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_recipeNo015_SigSegvNoHandler_callRiskyCodeNoHandler
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
