/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class recipeNo015_SigSegv */

#ifndef _Included_recipeNo015_SigSegv
#define _Included_recipeNo015_SigSegv
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     recipeNo015_SigSegv
 * Method:    callRiskyCode
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_recipeNo015_SigSegv_callRiskyCode
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
